### ISSUE TITLE
Empty Callback Graph generated

### ISSUE THREAD

**Issue by BernardoFuret** [theosotr/async-tajs#2]
Hello.

I'm having issues generating the callback graph, via the `-print-callback-graph` option. It always generates the empty graph.
```
digraph {
node [shape=circle]
}
```
Whether for my test files or for the ones provided by you (under `test-resources/src`). I also tested on the example code you have on the `README.md`. 

By using the option `-callback-graph-statistics` it always prints `Callback graph precision: N/A`.

I've been looking at the code and, on file CallbackGraph.java, `this.callbackGraph` seems to be, in fact, always empty.

Any idea why this happens?

Cheers

**Comment by theosotr** [comment]
enable asynchronous callbacks by passing the `--async-events` option.
